import db from "@/lib/db";

type MetadataProps = {
  params: {
    username: string;
  };
};

export async function generateMetadata({ params }: MetadataProps) {
  const user = await db.query.users.findFirst({
    where: (users, { eq }) => eq(users.username, `@${params.username}`),
  });

  if (user) {
    return {
      title: `${user.name} (${user.username}) / X`,
      description: `${user.name} profile`,
      referrer: "no-referrer",
    };
  }

  return {
    title: "Home / X",
    description: "Generated by create next app",
    referrer: "no-referrer",
  };
}

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
